### ISSUE TITLE
Error Result while converting BS date to AD

### ISSUE THREAD

**Issue by GaneshPandey** [SushilShrestha/DateConverterJS#1]
Expected:
BS: Poush 17 2002 ==> AD: 31 DEC 1945

Actual:
BS: Poush 17 2002 ==> AD: 31 DEC 1946

**Comment by SushilShrestha** [comment]
Thanks @GaneshPandey, for pointing this bug out.

**Comment by SushilShrestha** [comment]
Fixed in #v1.0.8 😁
